import { VehicleCardProps, BranchProps, InquiryProps, SellRequestProps } from "@types";

export const mockVehicles: VehicleCardProps[] = [
  {
    id: "1",
    stockNumber: "BW-001",
    make: "Toyota",
    model: "Land Cruiser Prado",
    year: 2021,
    price: 95000000,
    mileage: 42000,
    fuelType: "Diesel",
    transmission: "Automatic",
    status: "AVAILABLE",
    branch: "Dar es Salaam",
    primaryImage: "/hero.png",
    isFeatured: true,
  },
  {
    id: "2",
    stockNumber: "BW-002",
    make: "Nissan",
    model: "X-Trail",
    year: 2020,
    price: 48000000,
    mileage: 61000,
    fuelType: "Petrol",
    transmission: "Automatic",
    status: "AVAILABLE",
    branch: "Arusha",
    primaryImage: "/hero.png",
    isFeatured: false,
  },
  {
    id: "3",
    stockNumber: "BW-003",
    make: "Toyota",
    model: "Hilux",
    year: 2022,
    price: 87000000,
    mileage: 18000,
    fuelType: "Diesel",
    transmission: "Manual",
    status: "RESERVED",
    branch: "Mwanza",
    primaryImage: "/hero.png",
    isFeatured: true,
  },
  {
    id: "4",
    stockNumber: "BW-004",
    make: "Honda",
    model: "CR-V",
    year: 2019,
    price: 42000000,
    mileage: 55000,
    fuelType: "Petrol",
    transmission: "Automatic",
    status: "AVAILABLE",
    branch: "Dodoma",
    primaryImage: "/hero.png",
    isFeatured: false,
  },
  {
    id: "5",
    stockNumber: "BW-005",
    make: "Mercedes-Benz",
    model: "C-Class",
    year: 2020,
    price: 68000000,
    mileage: 35000,
    fuelType: "Petrol",
    transmission: "Automatic",
    status: "SOLD",
    branch: "Dar es Salaam",
    primaryImage: "/hero.png",
    isFeatured: false,
  },
  {
    id: "6",
    stockNumber: "BW-006",
    make: "Suzuki",
    model: "Vitara",
    year: 2021,
    price: 38000000,
    mileage: 28000,
    fuelType: "Petrol",
    transmission: "Automatic",
    status: "AVAILABLE",
    branch: "Arusha",
    primaryImage: "/hero.png",
    isFeatured: true,
  },
  {
    id: "7",
    stockNumber: "BW-007",
    make: "Toyota",
    model: "RAV4",
    year: 2022,
    price: 72000000,
    mileage: 12000,
    fuelType: "Hybrid",
    transmission: "Automatic",
    status: "AVAILABLE",
    branch: "Dar es Salaam",
    primaryImage: "/hero.png",
    isFeatured: false,
  },
  {
    id: "8",
    stockNumber: "BW-008",
    make: "BMW",
    model: "X3",
    year: 2021,
    price: 82000000,
    mileage: 30000,
    fuelType: "Diesel",
    transmission: "Automatic",
    status: "RESERVED",
    branch: "Mwanza",
    primaryImage: "/hero.png",
    isFeatured: false,
  },
  {
    id: "9",
    stockNumber: "BW-009",
    make: "Nissan",
    model: "Note",
    year: 2019,
    price: 22000000,
    mileage: 70000,
    fuelType: "Petrol",
    transmission: "Automatic",
    status: "AVAILABLE",
    branch: "Dodoma",
    primaryImage: "/hero.png",
    isFeatured: false,
  },
];

export const mockBranches: BranchProps[] = [
  {
    id: "1",
    name: "Dar es Salaam",
    city: "Dar es Salaam",
    address: "Kariakoo, Dar es Salaam",
    phone: "+255 22 123 4567",
  },
  {
    id: "2",
    name: "Mwanza",
    city: "Mwanza",
    address: "Pamba Road, Mwanza",
    phone: "+255 28 123 4567",
  },
  {
    id: "3",
    name: "Arusha",
    city: "Arusha",
    address: "Sokoine Road, Arusha",
    phone: "+255 27 123 4567",
  },
  {
    id: "4",
    name: "Dodoma",
    city: "Dodoma",
    address: "Nyerere Road, Dodoma",
    phone: "+255 26 123 4567",
  },
];

export const mockInquiries: InquiryProps[] = [
  {
    id: "1",
    customerName: "John Mwakasege",
    phone: "+255 712 345 678",
    vehicleName: "2021 Toyota Land Cruiser Prado",
    vehicleId: "1",
    status: "NEW",
    date: "2026-02-28",
    agent: "Amina",
  },
  {
    id: "2",
    customerName: "Grace Kimaro",
    phone: "+255 754 321 987",
    vehicleName: "2020 Nissan X-Trail",
    vehicleId: "2",
    status: "CONTACTED",
    date: "2026-02-27",
    agent: "Joseph",
  },
  {
    id: "3",
    customerName: "Ali Hassan",
    phone: "+255 689 111 222",
    vehicleName: "2022 Toyota Hilux",
    vehicleId: "3",
    status: "NEGOTIATING",
    date: "2026-02-26",
    agent: "Amina",
  },
  {
    id: "4",
    customerName: "Mary Shayo",
    phone: "+255 765 444 555",
    vehicleName: "2019 Honda CR-V",
    vehicleId: "4",
    status: "CLOSED_WON",
    date: "2026-02-25",
    agent: "Joseph",
  },
  {
    id: "5",
    customerName: "Peter Ngowi",
    phone: "+255 712 999 888",
    vehicleName: "2021 Suzuki Vitara",
    vehicleId: "6",
    status: "CLOSED_LOST",
    date: "2026-02-24",
    agent: "Amina",
  },
];

export const mockSellRequests: SellRequestProps[] = [
  {
    id: "1",
    sellerName: "David Mollel",
    phone: "+255 754 111 222",
    make: "Toyota",
    model: "Corolla",
    year: 2018,
    askingPrice: 28000000,
    status: "PENDING",
    date: "2026-02-28",
  },
  {
    id: "2",
    sellerName: "Fatima Nassoro",
    phone: "+255 689 333 444",
    make: "Nissan",
    model: "Juke",
    year: 2017,
    askingPrice: 25000000,
    status: "INSPECTION_ASSIGNED",
    date: "2026-02-27",
  },
  {
    id: "3",
    sellerName: "Emmanuel Kaya",
    phone: "+255 712 555 666",
    make: "Honda",
    model: "Fit",
    year: 2016,
    askingPrice: 18000000,
    status: "INSPECTED",
    date: "2026-02-26",
  },
  {
    id: "4",
    sellerName: "Sarah Mushi",
    phone: "+255 765 777 888",
    make: "Toyota",
    model: "Vitz",
    year: 2019,
    askingPrice: 22000000,
    status: "APPROVED",
    date: "2026-02-25",
  },
];

export const mockDashboardStats = {
  totalVehicles: 156,
  availableVehicles: 98,
  inquiriesThisMonth: 47,
  pendingSellRequests: 12,
  totalVehiclesTrend: 8,
  availableTrend: -3,
  inquiriesTrend: 12,
  sellRequestsTrend: 5,
};

export const mockMonthlySales = [
  { month: "Sep", sales: 18 },
  { month: "Oct", sales: 24 },
  { month: "Nov", sales: 22 },
  { month: "Dec", sales: 31 },
  { month: "Jan", sales: 28 },
  { month: "Feb", sales: 35 },
];

export const mockInventoryByStatus = [
  { name: "Available", value: 98, color: "#059669" },
  { name: "Reserved", value: 23, color: "#D97706" },
  { name: "Sold", value: 35, color: "#DC2626" },
];
